<Project>

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Copyright>Copyright (c) 2026 adsefid.com</Copyright>
  </PropertyGroup>


  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Adsefid.Sdk.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
